name: autodokdor1
description: "AI Auto Doctor — OBD-II Car Diagnostic App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  percent_indicator: ^4.2.3
  animated_text_kit: ^4.2.2

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Database
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1

  # Bluetooth
  flutter_blue_plus: ^1.35.3

  # Network & API
  http: ^1.6.0
  flutter_dotenv: ^5.2.1


  # Utils
  intl: ^0.20.2
  permission_handler: ^12.0.1
  geolocator: ^13.0.2
  shared_preferences: ^2.3.5
  uuid: ^4.5.1
  equatable: ^2.0.7
  google_generative_ai: ^0.4.7
  flutter_blue_plus_winrt: ^0.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/lottie/


